name: baltini_kent
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  dio: ^5.1.0
  provider: ^6.0.0
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  group_button: ^5.2.2
  badges: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/icons_24/
    - assets/icons/icons_44/
    - assets/icons/icons_80/
    - assets/images/
    - assets/images/product/
    - assets/nav_icon/
    - assets/splashscreen/

  fonts:
      - family: Futura
        fonts:
          - asset : assets/fonts/Futura_Medium_BT.ttf
            weight : 500
          - asset : assets/fonts/Futura_Medium_Italic_Font.ttf
            weight : 500
            style : italic
          - asset : assets/fonts/Futura_Bold_Font.ttf
            weight : 800
          - asset : assets/fonts/Futura_Bold_Italic_Font.ttf
            weight : 800
            style : italic
          - asset : assets/fonts/Futura_Book_Font.ttf
            weight : 300
          - asset : assets/fonts/Futura_Book_Italic_Font.ttf
            weight : 300
            style : italic
